
server:
  port: 8050
  name: Ms Funcionario

spring:
  application:
    name: ms-funcionario
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27017/user-blood-testing?retryWrites=true&w=majority

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: local-vh
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka